source 'https://rubygems.org'

gem 'certified'
gem 'httparty'
gem 'openssl'
gem 'puma'
gem 'shopify_api', '~> 13.3'
gem 'shopify_app', '~> 21.8'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'sinatra-cors'

gem 'rubocop', '~> 1.59'
